services:
  docker:
    image: docker:dind
    container_name: docker
    privileged: true
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins_home:/var/jenkins_home
      # - /var/jenkins_home:/var/jenkins_home
      - jenkins_docker_certs:/certs/client
    ports:
      - '127.0.0.1:2376:2376'
    command: --storage-driver overlay2
    restart: "unless-stopped"

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    container_name: jenkins
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    volumes:
      - jenkins_home:/var/jenkins_home
      # - /var/jenkins_home:/var/jenkins_home
      - jenkins_docker_certs:/certs/client:ro
    ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:50000:50000'
    links:
      - docker:docker
    restart: "unless-stopped"

  jfrog:
    image: docker.bintray.io/jfrog/artifactory-oss
    container_name: jfrog
    networks:
      - jenkins
    ports:
      - '127.0.0.1:8081:8081'
      - '127.0.0.1:8082:8082'
      - '127.0.0.1:8046:8046'
      - '127.0.0.1:8049:8049'
      - '127.0.0.1:8070:8070'
    volumes:
      - jfrog_home:/var/opt/jfrog/artifactory
      # - /var/jfrog_home:/var/opt/jfrog/artifactory
    restart: "unless-stopped"

networks:
  jenkins:

volumes:
  jenkins_home:
  jfrog_home:
  jenkins_docker_certs:
